FROM php:7.2-cli
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y libpq-dev zlib1g-dev wget unzip libpng-dev procps net-tools
RUN docker-php-ext-install -j$(nproc) pgsql pdo_pgsql zip pdo_mysql gd

# running  this before COPY . /var/www/html help with caching composer installation
COPY --chown=www-data:www-data install_composer.sh /var/www/html/
RUN /bin/sh install_composer.sh --install-dir=/usr/local/bin --filename=composer

COPY --chown=www-data:www-data . /var/www/html

EXPOSE 6001
CMD ["/usr/local/bin/php", "/var/www/html/artisan", "websockets:serve"]
